### ISSUE TITLE
ReferenceError: createSnippet is not defined

### ISSUE THREAD

**Issue by peernohell** [weglot/integration-hooks#1]
When I run your script it crash due to missing createSnippet import.

```
(node:27072) UnhandledPromiseRejectionWarning: ReferenceError: createSnippet is not defined
    at snippet (/Users/peernohell/projects/integration-hooks/webflow/hook.js:23:19)
    at /Users/peernohell/projects/integration-hooks/webflow/hook.js:73:43
    at Array.map (<anonymous>)
    at /Users/peernohell/projects/integration-hooks/webflow/hook.js:69:15
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by etiennecaldo** [comment]
Same issue here

**Comment by nico2che** [comment]
Thank you!
